### ISSUE TITLE
Unable to change the default layout template

### ISSUE THREAD

**Issue by midami** [godaddy/wp-ascension-theme#73]
How do I change the default page layout from two columns (current default, bordered in blue) to one column (circled in red)? (see photo)
Thank you!
![defaultpagelayout](https://user-images.githubusercontent.com/30373034/28492373-3311be34-6ed0-11e7-857c-bbdae66f34ba.png)

**Comment by midami** [comment]
@EvanHerman you seem to be very helpful :)

**Comment by EvanHerman** [comment]
Hi @midami,

I did some investigating, and it looks like the default layout is the `two-column-default` layout. In previous versions we had a few customizer settings that allowed the user to toggle the default layout for all pages, but this was since removed.

It looks like the default layout is still referencing the old customizer options, so at the moment it doesn't appear there is any way through the UI to update the default layout.

However, since the default layout value is just a customizer option, you can still update the value to set use a different default template by adding a small snippet to your website.

The first option, and a little more involved, is to setup an MU plugin where you can add this code to. We have some documentation setup here explaining how to setup an MU plugin on your site. Once you have your MU plugin setup, add the following snippet to it, and save the file:

```php
set_theme_mod( 'layout', 'one-column-wide' );
```

Once saved, reload your site, and you the default template should now be set to use the template you have circled.

The second option is to add the code above directly to the bottom of your themes functions.php file, save the file, and then reload your site. This is not the recommended method since with each theme update the code will be removed, but since we just need to update a value in the database you can add it here and then remove it when the template works as you need it to.

*Note:* Since the value in the database just needs to be updated one time it may be overkill to setup an MU plugin to run this code one time. Whichever route you take, when the default template is working as you expect it to you can delete the MU plugin or remove the code snippet from your theme file.

Moving forward, we will have to come up with a method for users to update the default template without having to write any code - so thank you for bringing this to our attention. I'm going to tag this and work on a patch in the coming days.

Evan

_Additional Notes:_
The possible options for the templates are:
- one-column-wide
- one-column-narrow
- two-column-default
- two-column-reversed
- three-column-default
- three-column-center
- three-column-reversed

You can replace 'one-column-wide' with any of the above values. (I am more-or-less adding the list above as a reference for anyone else who may encounter this bug and want to reference a different template).

**Comment by midami** [comment]
Hi @EvanHerman.
Thank you so much for your super comprehensive, informative, helpful, and speedy(!) reply!
Your solution worked and I've made a note of the update "warning" you included. And if you can make it so that users can more easily select their preferred default layout, I think that would be great!
Your help is much appreciated!

**Comment by EvanHerman** [comment]
Just as a follow up here, for anyone who has installed Primer from version 1.5.0+, you can simply use a filter to alter the default layout instead of updating the `theme_mod` option.

Adding the following filter to the MU plugin outlined above should be enough to change the default layout (assuming there is no `layout` theme mod previously set).

```php
add_filter( 'primer_default_layout', function () {
	return 'one-column-wide';
} );
```
