### ISSUE TITLE
How to centre the hero text and button

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-ascension-theme#74]
Hi all,

I'm new to Github and Wordpress websites but I do have some basic knowledge of HTML and CSS.

The default position of the text and button in the hero section is right aligned but I would prefer it centred. Please can anyone advise how to do this? I have found the style sheet but can't locate the piece of code I need to edit. Is it as simple as changing it from right to centre? I have a feeling it won't be! Here is the current link http://ab2.252.myftpupload.com

Thanks, Mark

**Comment by EvanHerman** [comment]
Hi @markvidler84 

You should be able to tweak the CSS to get the text aligned how you'd like. The most important thing to note is that you don't want to edit the style.css file directly, as every time the theme is updated your customizations will be removed. You'll want to add the custom CSS to the themes 'Additional CSS' section inside of the customizer. However, you can certainly use the existing styles as a starting point to add to your additional CSS section.

You'll have to adjust the styles for the containers since there is a left padding on the hero text widget.

```css
.primer-hero-text-widget {
   width: 60%;
   max-width: 735px;
   margin: 0 auto;
   text-align: center;
}

@media only screen and (min-width: 40.063em) {
   .home .hero aside {
      padding: 0;
   }
}
```

If you want to make changes for mobile devices _only_ you can use the breakpoint:
```css
@media only screen and (max-width: 40.063em) {

   /** Mobile Styles Here **/

}
```
(The difference between this block and the previous is the min/max-width)

**Comment by markvidler84** [comment]
Thanks Evan. I'll try adding that as you suggested in the additional CSS section.
Will that apply it to the other pages? And will it also centre the button on the homepage?

Thanks again!

**Comment by EvanHerman** [comment]
Hi @markvidler84 
I'm unsure of what you mean by central. Do you mean centered on the page? You said you wanted the container centered in your original post.

**Comment by markvidler84** [comment]
Hi Evan, the text and button are now centre aligned which is great :)
But if you look they are not centred to the middle of the page, they are more on the left hand side http://ab2.252.myftpupload.com

Thanks

**Comment by EvanHerman** [comment]
@markvidler84 

Have you tried adding that slight tweak I provided above?

**Comment by markvidler84** [comment]
Sorry I missed the tweak. I've tried it and it works perfectly! Thank you! :)

Just one more thing if I could ask. How would I go about doing the same on the service page and is there a way I can set the height to be the same as the homepage? http://ab2.252.myftpupload.com/services/

**Comment by EvanHerman** [comment]
Awesome. You should be able to target the page title inside of the `.hero` element. If you use the `<body>` class to target the services page by page ID you can adjust the styles just on the services page.

`page-id-158`

```css
.page-id-158 .hero .page-header h1 {
   text-align: center;
   padding: 7.6% 50px;
}
```

It is worth noting that the services page may not _always_ mirror the height of the home page, since the content lengths differ and the height of the hero is directly related to the padding of the `h1` element.

For example, if you alter the homepage hero text widget, the height of the homepage hero will most likely change - which would then cause the services page to no longer match the homepage. It also will vary based on the device you are viewing it on. On a laptop (such as I am using) the text is going to be more condensed on the homepage, and will cause the text to expand across multiple lines. If you were to view it on a larger monitor the content length will be shorter - which will most likely cause the two pages to visually appear different.

You can always add a `height` declaration to the `.home .hero` and the `.page-id-158 .hero` so regardless of the screen size the height of the containers match each other.

```css
.home .hero,
.page-id-158 .hero {
   height: 450px;
}
```

but this will also cause the hero element to be 450px in mobile devices. You can use the breakpoint I provided above to tweak the homepage hero height on mobile devices as you see fit.


Evan

**Comment by markvidler84** [comment]
Thanks Evan, you're a genius! I've made the hero bigger on each page which is perfect as the image inside looked a bit small before. I don't think I will make them a fixed height though because like you say they will stay that big on mobile.

One last thing that is bugging me is that in the footer the 'follow us' column doesn't align left with the body section above (which has a larger margin). Is there any way to fix that? I'm guessing I need to make the left margin bigger in both columns of the footer?

Thanks again, sorry for all the questions! :)

**Comment by markvidler84** [comment]
Hi Evan, thanks for getting back. That's strange as I don't remember touching any of the CSS for the footer. Maybe I've checked or unchecked something in the customisation settings?

**Comment by EvanHerman** [comment]
What is the layout method to set in the customizer? Fixed or Fluid? I believe if set to 'Fluid' the margins will disappear and the widgets will reach near the edge of the page.

**Comment by markvidler84** [comment]
Thanks! Ah I did change it to fluid so thats why the margin disappeared. That's a shame as the hero and top menu look better fun width.

**Comment by markvidler84** [comment]
Do you know if there is a way to have the hero fixed but have it wider? That would solve my issue in the footer. Thanks again

**Comment by EvanHerman** [comment]
I'm not entirely sure, I'm sure you can use CSS to achieve what you are after. I would recommend posting in the general support forum on WordPress.org. The people there are generally very helpful and would be more than happy to provide you with some quality code snippets.

This forum is more or less for technical bugs that are encountered when using the theme.

https://wordpress.org/support/forum/wp-advanced/
