### ISSUE TITLE
Hero Image Is Not Mobile Friendly

### ISSUE THREAD

**Issue by prajwalchandra** [godaddy/wp-ascension-theme#76]
Hi,

I am using this theme for one of my websites and it works and looks great. But I have these following issues, apart from which everything is fine.

1) I am having difficulty with the header image in the Ascension theme. The title of the page is displayed in the header image and the header image is cropped depending on how much text is in the title. I want the header image to be displayed fully across all the pages. Does anybody have any suggestions?

Also, the hero image is not mobile friendly. It doesn't display full and takes its own dimension on the mobile and and displays the title on it whole differently.

2) Is there any way to remove the header image from the posts page? I see no option to do that. I want the header images on the "Page" page but not on the Posts page.

Awaiting your response. Thanks in advance.

Regards,
Prajwal

**Comment by EvanHerman** [comment]
Hi @prajwalchandra 

Do you have a link to your site as an example?

**Comment by prajwalchandra** [comment]
Hi Evan,

Thanks for the reply.

Here is the website link: http://cartellers.com/

**Comment by EvanHerman** [comment]
Hi @prajwalchandra 

The only way to display the image in your header as a full image on every device would be to set the `.hero` background image to contain. (It is set to cover by default)

```css
.hero {
   background-size: contain;
} 
```

 But you'll notice on mobile devices that there is now a gap beneath the hero image, since the parent contain doesn't shrink down along with the image due to the text size. You will have to play around with breakpoints and different values for the font-sizes & background-image cover/contain to get things looking right.

As for your second question, you can remove the background image on posts using the following CSS:

```css
body.single-post .hero {
   background-image: none;
}
```

**Comment by prajwalchandra** [comment]
Hi Evan,

Thanks for the codes :)

They did bring in some changes but did not resolve my issues.

1) The below hero image code actually made the hero image on the mobile
device to stay intact, but what actually happened is, the hero title given
to it did not fit within the hero image (it wasn't fitting even before).
Screenshots below will give you a much better picture. I want the image to
retain like it is in below screesnhot(with the code appended) but also the
tile to remain within it. But it works fine on Desktop. Please help me with
the mobile device.

.hero {
   background-size: contain;
}


2) The second code resulted in removing the header image from the post
page. But I actually want that entire header image placement to go off.
Screenshot below.

body.single-post .hero {
   background-image: none;
}


with the code appended
[image: Inline image 1]

without the code
  [image: Inline image 2]


[image: Inline image 3]

Kind regards,
Prajwal Chandra
